language: dart

dart:
  - stable
  - '2.7.2'
  - dev

# Re-use downloaded pub packages everywhere.
cache:
  directories:
    - $HOME/.pub-cache

script:
- pub run dart_dev format --check
- dartanalyzer .
- pub run dependency_validator
- pub run test
