language: dart

dart:
  - stable

# Re-use downloaded pub packages everywhere.
cache:
  directories:
    - $HOME/.pub-cache

script:
- pub run dart_dev format --check
- dartanalyzer .
- pub run dependency_validator -i build_runner,build_test,dart_style,pedantic
- pub run test

