targets:
  $default:
    sources:
      include:
        - "lib/**"
        - "test/**"
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          include:
            - "test/**.dart"
