name: codemod
private: true
version: 0.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  analyzer: ^0.33.6+1
  args: ^1.5.1
  io: ^0.3.3
  logging: ^0.11.3+2
  path: ^1.6.2
  source_span: ^1.4.1
  stack_trace: ^1.9.3

dev_dependencies:
  dart_dev: ^2.0.1
  dart_style: ^1.2.0
  dependency_validator: ^1.2.3
  mockito: ^4.0.0
  pedantic: ^1.4.0
  test: ^1.5.1+1